
name: flutter_auth_app
description: "A new Flutter project for authentication."

publish_to: 'none' # Prevent accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.2
  http: ^1.2.2
  shared_preferences: ^2.1.1
  json_annotation: ^4.7.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+3
  intl: ^0.18.0
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/doc.png  # Make sure this file path is correct.


