name: flutter_auth_app
description: "A new Flutter project for authentication."

publish_to: 'none' # Prevent accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.2
  http: ^1.2.2
  shared_preferences: ^2.1.1
  json_annotation: ^4.7.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+3
  intl: ^0.18.0
  socket_io_client: ^2.0.0
  provider: ^6.0.5        # State management
  path_provider: ^2.0.15  # Accessing the file system
  flutter_secure_storage: ^9.0.1 # Secure storage for sensitive data
  dio: ^5.3.2             # Advanced HTTP requests
  logger: ^1.1.0          # Logging for debugging
  url_launcher: ^6.1.7    # To open URLs, including PDFs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6  # Generates code for json_annotation and other tools
  google_sign_in: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/doc.png  # Ensure this file exists and the path is correct.
    - assets/         # Include all files in the assets folder